### PR TITLE
Export paths

### LINKED ISSUE #4: add a method for obtaining the paths to keys and certificates on disk
It would be lovely to be able to access the existing keys and certificates on disk.  Currently I just save my own copy with a known name, but that just feels ugly.

### PR DESCRIPTION
**Pull request by mygnu**
closes #4

### CODE REVIEW

**Review by algesten — APPROVED** [review]
Looks good! ✨

**Comment by algesten** [comment]
@mygnu The branch has some conflicts. Maybe drop the dependency update since I like doing that myself?

**Comment by mygnu** [comment]
Thanks rebased on current master

**Comment by algesten** [comment]
@mygnu Since both your PR are about opening up acme-lib to allow for some different usage, I assume this is to do with the persistence? What is the problem with the `Persist` trait? Can we discuss it more generally in #18?

**Pull request closed without merging**
