### PR TITLE
Update to ureq v2

### LINKED ISSUE #50: `ureq` v2?
The current `ureq` 1.5.5 dependency is pulling in an extra old version of `rustls` (0.19); since I noticed that you're also the author of `ureq`, is this an easy update?

### PR DESCRIPTION
**Pull request by trevyn**
Closes #50
Closes #32

### CODE REVIEW

**Comment by a-rustacean** [comment]
## ⚠️  **Important**  ⚠️

Hello @algesten,

I wanted to bring to your attention that there was a significant **security vulnerability** in previous versions of ureq due to a known issue with older versions of webpki, as detailed in [this issue](https://github.com/briansmith/webpki/issues/69).

I kindly request your assistance in addressing this matter and would appreciate it if you could look into this for further investigation and resolution.

**Review by algesten — APPROVED** [review]
Let's ship it!

**Comment by algesten** [comment]
Thanks!

**Comment by algesten** [comment]
This is published as 0.9.0

**Comment by a-rustacean** [comment]
Thanks @algesten for your quick support and assistance.

**Pull request merged**
